### ISSUE TITLE
Sound files under Damascus-Wörterbuch have positioning issues on smaller devices.

### ISSUE THREAD

**Issue by asilcetin** [acdh-oeaw/vicav-app#24]

**Comment by Dominik-rueth** [comment]
![image](https://user-images.githubusercontent.com/78848169/220096854-20ebf279-cf2f-4f69-b84a-68b0af5b272d.png)
I do not manage to download the sound files on Firefox 110.0, Mozilla Firefox Snap for Ubuntu
because the sound files do not appear above or below the mouse pointer, but further up so I cannot click on them.
Feature request: Couldn't you just make a zip file with all sound files available?

**Comment by Dominik-rueth** [comment]
CC: @saraedum

**Comment by saraedum** [comment]
Adding the following to the CSS works around the issue:
```
.audio {
position: unset;
}
```

All the audios are then just shown all the time: 
![image](https://user-images.githubusercontent.com/373765/220198383-d1522181-1683-45c4-997a-31954c281b1c.png)

In the browser developer tools, click on the `+` to add that rule:

![image](https://user-images.githubusercontent.com/373765/220198526-2835ef7c-676c-4dc8-a643-b32bda0a07a2.png)

**Comment by simar0at** [comment]
Sorry, the solution is too far away from the intended functionality of the site.
We tried to fix the root cause of the problem. The result is now live.
